### ISSUE TITLE
How to install and use it with slicer 4.13.0?

### ISSUE THREAD

**Issue by cyberlark** [mikebind/SlicerStitchImageVolumes#1]
hi, I'm very interested in this extension module, but I could not install and get it run with slicer 4.13. 

so, would you please give me some instructions on the installation?  thanks.

**Comment by mikebind** [comment]
This module has not been bundled into an extension that can be installed using the Extensions Manager, instead you need to add it through a straightforward but more manual process:
* Download this repository as a .zip file, 
* then unzip, everything will be in a folder called SlicerStitchImageVolumes-main.  
* Open Slicer, then open Application Settings (ctrl-2), then select "Modules" on the left, and then click on the ">>" button to the right of the Additional Module Paths section, then click the "Add" button.  
* Navigate to the unzipped SlicerStitchImageVolumes-main folder and select it.  Restart Slicer, and the "Stitch Volumes" module should now be available.  

This module definitely works in versions 4.11-4.13, and likely works in at least 4.10 as well. 

If I can get to it, this module may also be added to the SlicerSandbox extension soon, which would provide a way for it to be installed via the Extensions Manager, but that is not yet available.
